---
abstract: 'Common utilities for transforming files'
author:
  - 'Mike DeLaurentis <delaurentis@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RUM-Index
provides:
  RUM::Common:
    file: lib/RUM/Common.pm
  RUM::Config:
    file: lib/RUM/Config.pm
  RUM::FileIterator:
    file: lib/RUM/FileIterator.pm
  RUM::Script:
    file: lib/RUM/Script.pm
    version: 0.01
  RUM::Sort:
    file: lib/RUM/Sort.pm
    version: 0.01
  RUM::Subproc:
    file: lib/RUM/Subproc.pm
  RUM::TestUtils:
    file: lib/RUM/TestUtils.pm
  RUM::Workflow:
    file: lib/RUM/Workflow.pm
requires:
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
